fixed Exploit_OlympusDAO match issue
coinspect/learn-evm-attacks pull request #49
Opened 2022-12-23 06:37 UTC by ephz3nt

2022-12-26 12:23 UTC, juli requested changes
please explain

2022-12-26 15:58 UTC, ephz3nt commented
detail:
Bond_OlympusDAO: [Bond_OlympusDAO ](https://github.com/coinspect/learn-evm-attacks/tree/master/test/Bad_Data_Validation/Bond_OlympusDAO)
Reproduce: `forge test --match-contract Exploit_OlympusDAO -vvv`
if run this reproduce on forge will return issue: `No tests match the provided pattern:`
        `match-contract: Exploit_OlympusDAO`
because [Bond_OlympusDAO.attack.sol](https://github.com/coinspect/learn-evm-attacks/blob/master/test/Bad_Data_Validation/Bond_OlympusDAO/Bond_OlympusDAO.attack.sol) contract name is: `Exploit_OlympusDao`
change to uppercase: `Exploit_OlympusDao => Exploit_OlympusDAO`
will  fixed

2023-01-30 21:37 UTC, joaquinlpereyra commented
@ephz3nt Hi, sorry for taking so long! Holidays 🎄 you understand. 

I think the change is quite arbitrary, spelling either `Dao` following camel case or `DAO` respecting a bit more the initials can lead to confusion either way.

For now I think we are gonna leave it as is.

2023-01-30 21:37 UTC, closed without merging

2023-01-30 21:37 UTC, joaquinlpereyra commented
@ephz3nt Hi, sorry for taking so long! Holidays 🎄 you understand. 

I think the change is quite arbitrary, spelling either `Dao` following camel case or `DAO` respecting a bit more the initials can lead to confusion either way.

For now I think we are gonna leave it as is.